config/routes.rb
Rails.application.routes.draw do
  root 'logs#index'
  resources :logs
  resources :models
  get 'logs/statuses' => 'logs#statuses', as: :statuses_log

end

app/models/log.rb
class Log < ActiveRecord::Base
end

app/models/model.rb
class Model < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_action :set_log, only: [:show, :edit, :update, :destroy]

  # GET /logs
  # GET /logs.json
  def index
    @logs = Log.all.order('created_at DESC').page params[:page]
    @long_duration_logs = Log.order(duration: :desc).limit(10)
    @statuses = Log.group(:status).count
    @methods = Log.group(:method).count
    @controllers = Log.group(:controller).count
  end

  def statuses
    render json: Log.group(:status).count
  end

  # GET /logs/1
  # GET /logs/1.json
  def show
  end

  # GET /logs/new
  def new
    @log = Log.new
  end

  # GET /logs/1/edit
  def edit
  end

  # POST /logs
  # POST /logs.json
  def create
    @log = Log.new(log_params)

    respond_to do |format|
      if @log.save
        format.html { redirect_to @log, notice: 'Log was successfully created.' }
        format.json { render :show, status: :created, location: @log }
      else
        format.html { render :new }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /logs/1
  # PATCH/PUT /logs/1.json
  def update
    respond_to do |format|
      if @log.update(log_params)
        format.html { redirect_to @log, notice: 'Log was successfully updated.' }
        format.json { render :show, status: :ok, location: @log }
      else
        format.html { render :edit }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logs/1
  # DELETE /logs/1.json
  def destroy
    @log.destroy
    respond_to do |format|
      format.html { redirect_to logs_url, notice: 'Log was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_log
      @log = Log.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def log_params
      params.fetch(:log, {})
    end
end

app/controllers/models_controller.rb
class ModelsController < ApplicationController
  before_action :set_model, only: [:show, :edit, :update, :destroy]

  # GET /models
  # GET /models.json
  def index
    @models = Model.all
  end

  # GET /models/1
  # GET /models/1.json
  def show
  end

  # GET /models/new
  def new
    @model = Model.new
  end

  # GET /models/1/edit
  def edit
  end

  # POST /models
  # POST /models.json
  def create
    @model = Model.new(model_params)

    respond_to do |format|
      if @model.save
        format.html { redirect_to @model, notice: 'Model was successfully created.' }
        format.json { render :show, status: :created, location: @model }
      else
        format.html { render :new }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /models/1
  # PATCH/PUT /models/1.json
  def update
    respond_to do |format|
      if @model.update(model_params)
        format.html { redirect_to @model, notice: 'Model was successfully updated.' }
        format.json { render :show, status: :ok, location: @model }
      else
        format.html { render :edit }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /models/1
  # DELETE /models/1.json
  def destroy
    @model.destroy
    respond_to do |format|
      format.html { redirect_to models_url, notice: 'Model was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_model
      @model = Model.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def model_params
      params.require(:model).permit(:name, :atribute)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fluentd</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/logs/_form.html.erb
<%= form_for @log, :html => { :class => "form-horizontal log" } do |f| %>

  <% if @log.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@log.errors.count, "error") %> prohibited this log from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @log.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :info, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :info, :class => 'form-control' %>
    </div>
    <%=f.error_span(:info) %>
  </div>
  <div class="form-group">
    <%= f.label :method, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :method, :class => 'form-control' %>
    </div>
    <%=f.error_span(:method) %>
  </div>
  <div class="form-group">
    <%= f.label :path, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :path, :class => 'form-control' %>
    </div>
    <%=f.error_span(:path) %>
  </div>
  <div class="form-group">
    <%= f.label :format, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :format, :class => 'form-control' %>
    </div>
    <%=f.error_span(:format) %>
  </div>
  <div class="form-group">
    <%= f.label :controller, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :controller, :class => 'form-control' %>
    </div>
    <%=f.error_span(:controller) %>
  </div>
  <div class="form-group">
    <%= f.label :action, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :action, :class => 'form-control' %>
    </div>
    <%=f.error_span(:action) %>
  </div>
  <div class="form-group">
    <%= f.label :status, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :status, :class => 'form-control' %>
    </div>
    <%=f.error_span(:status) %>
  </div>
  <div class="form-group">
    <%= f.label :duration, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :duration, :class => 'form-control' %>
    </div>
    <%=f.error_span(:duration) %>
  </div>
  <div class="form-group">
    <%= f.label :view, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :view, :class => 'form-control' %>
    </div>
    <%=f.error_span(:view) %>
  </div>
  <div class="form-group">
    <%= f.label :db, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :db, :class => 'form-control' %>
    </div>
    <%=f.error_span(:db) %>
  </div>
  <div class="form-group">
    <%= f.label :location, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :location, :class => 'form-control' %>
    </div>
    <%=f.error_span(:location) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                logs_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/logs/edit.html.erb
<%- model_class = Log -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/logs/index.html.erb
<%- model_class = Log -%>
<div class="container-fluid">
<div class="page-header">
  <h1>The Logs.</h1>
</div>
<div class="row">
   <div class="col-xs-12">
    <h3 class="text-center">Top 10 duration requests</h3>
  </div>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:method) %></th>
      <th><%= model_class.human_attribute_name(:path) %></th>
      <th><%= model_class.human_attribute_name(:controller) %></th>
      <th><%= model_class.human_attribute_name(:action) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:duration) %></th>
      <th><%= model_class.human_attribute_name(:location) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @long_duration_logs.each do |log| %>
      <tr>
        <td><%= link_to log.id, log_path(log) %></td>
        <td><%= log.method %></td>
        <td><%= log.path %></td>
        <td><%= log.controller %></td>
        <td><%= log.action %></td>
        <td><%= log.status %></td>
        <td><b><%= log.duration %></b></td>
        <td><%= log.location %></td>
        <td><%=l log.created_at %></td>
        <td>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      log_path(log),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="row">
    <div class="col-xs-12 col-sm-4">
      <h4 class="text-center">Status</h4>
      <%= pie_chart @statuses, donut: true %>
    </div>
    <div class="col-xs-12 col-sm-4">
      <h4 class="text-center">Methods</h4>
       <%= pie_chart @methods, donut: true %>
    </div>
    <div class="col-xs-12 col-sm-4">
      <h4 class="text-center">Controllers</h4>
      <%= pie_chart @controllers, donut: true %>
    </div>
</div>

<div class="row">
   <div class="col-xs-12">
     <div>
        <h3 class="text-center pt-5">All logs</h3>
     </div>
  </div>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:method) %></th>
      <th><%= model_class.human_attribute_name(:path) %></th>
      <th><%= model_class.human_attribute_name(:controller) %></th>
      <th><%= model_class.human_attribute_name(:action) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:duration) %></th>
      <th><%= model_class.human_attribute_name(:location) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @logs.each do |log| %>
      <tr>
        <td><%= link_to log.id, log_path(log) %></td>
        <td><%= log.method %></td>
        <td><%= log.path %></td>
        <td><%= log.controller %></td>
        <td><%= log.action %></td>
        <td><%= log.status %></td>
        <td><%= log.duration %></td>
        <td><%= log.location %></td>
        <td><%=l log.created_at %></td>
        <td>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      log_path(log),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<span class="pagination"> <%= paginate @logs %> </span>
</div>

app/views/logs/new.html.erb
<%- model_class = Log -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/logs/show.html.erb
<%- model_class = Log -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:info) %>:</strong></dt>
  <dd><%= @log.info %></dd>
  <dt><strong><%= model_class.human_attribute_name(:method) %>:</strong></dt>
  <dd><%= @log.method %></dd>
  <dt><strong><%= model_class.human_attribute_name(:path) %>:</strong></dt>
  <dd><%= @log.path %></dd>
  <dt><strong><%= model_class.human_attribute_name(:format) %>:</strong></dt>
  <dd><%= @log.format %></dd>
  <dt><strong><%= model_class.human_attribute_name(:controller) %>:</strong></dt>
  <dd><%= @log.controller %></dd>
  <dt><strong><%= model_class.human_attribute_name(:action) %>:</strong></dt>
  <dd><%= @log.action %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= @log.status %></dd>
  <dt><strong><%= model_class.human_attribute_name(:duration) %>:</strong></dt>
  <dd><%= @log.duration %></dd>
  <dt><strong><%= model_class.human_attribute_name(:view) %>:</strong></dt>
  <dd><%= @log.view %></dd>
  <dt><strong><%= model_class.human_attribute_name(:db) %>:</strong></dt>
  <dd><%= @log.db %></dd>
  <dt><strong><%= model_class.human_attribute_name(:location) %>:</strong></dt>
  <dd><%= @log.location %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              logs_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_log_path(@log), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              log_path(@log),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/models/_form.html.erb
<%= form_for @model, :html => { :class => "form-horizontal model" } do |f| %>

  <% if @model.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@model.errors.count, "error") %> prohibited this model from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @model.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :atribute, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :atribute, :class => 'form-control' %>
    </div>
    <%=f.error_span(:atribute) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                models_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/models/edit.html.erb
<%- model_class = Model -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/models/index.html.erb
<%- model_class = Model -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:atribute) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @models.each do |model| %>
      <tr>
        <td><%= link_to model.id, model_path(model) %></td>
        <td><%= model.name %></td>
        <td><%= model.atribute %></td>
        <td><%=l model.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_model_path(model), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      model_path(model),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_model_path,
            :class => 'btn btn-primary' %>

app/views/models/new.html.erb
<%- model_class = Model -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/models/show.html.erb
<%- model_class = Model -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @model.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:atribute) %>:</strong></dt>
  <dd><%= @model.atribute %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              models_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_model_path(@model), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              model_path(@model),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>